DOMAIN = "wsound"

PLATFORMS = ["switch", "button", "number", "select", "sensor", "binary_sensor"]

CONF_HOST = "host"
CONF_PORT = "port"
DEFAULT_PORT = 80

# Options
CONF_FOLDERS_COUNT = "folders_count"
CONF_POLL_INTERVAL = "poll_interval"

DEFAULT_FOLDERS_COUNT = 10
DEFAULT_POLL_INTERVAL = 5

DEFAULT_FOLDER = "01"

VOLUME_MIN = 0
VOLUME_MAX = 30
VOLUME_DEFAULT = 10

FADE_MIN = 0
FADE_MAX = 120
FADE_DEFAULT = 10

DURATION_MIN = 10
DURATION_MAX = 1800
DURATION_DEFAULT = 300
